package cabbooking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import cabbooking.Wallet_page;
import javax.swing.JOptionPane;
import cabbooking.driver_info;
import java.text.SimpleDateFormat;
import java.util.Date;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Final_Form.java
 *
 * Created on 2 Nov, 2019, 11:40:42 PM
 */

/**
 *
 * @author Dell
 */
public class Final_Form extends javax.swing.JFrame {

    /** Creates new form Final_Form */
    String uid;
    int total_time;
    public Final_Form(String s) {
        initComponents();
        uid=s;
    }
    public Final_Form() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        cb2 = new javax.swing.JComboBox();
        btn1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 25, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel1.setText("BOOK YOUR RIDE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel2.setText("PICKUP POINT :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel3.setText("DROP POINT :");

        cb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        cb1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                cb1ComponentAdded(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cb2.setFont(new java.awt.Font("Tahoma", 1, 18));
        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));

        btn1.setFont(new java.awt.Font("Tahoma", 1, 18));
        btn1.setText("BOOK");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton2.setText("ADD MONEY TO WALLET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        l1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 51, 51));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton4.setText("GO TO MAIN PAGE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(231, 231, 231)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cb1ComponentAdded
        // TODO add your handling code here:
}//GEN-LAST:event_cb1ComponentAdded

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed

try
{
   Class.forName("com.mysql.jdbc.Driver");

   Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
   for(int i=1;i<7;i++)
   {
       String sql="Select * from driver where serialnumber=?";
       PreparedStatement pst = con.prepareStatement(sql);
       pst.setString(1,Integer.toString(i));
        ResultSet rs = pst.executeQuery();
        if(rs.next())
        {
            String busy=rs.getString("busy");
            String us=rs.getString("curruser");
            String currtime=rs.getString("currtime");
            String dur=rs.getString("duration");
            String ne=rs.getString("nextstop");
            if(busy.equals("1"))
            {
                
                Date date=new Date();
         SimpleDateFormat sdf=new SimpleDateFormat("hh:mm:ss");
         String str=sdf.format(date);
         System.out.println(str);
         char[] ch=str.toCharArray();
         int curt=(((int)ch[0]-48)*10+(int)ch[1]-48)*60+((int)ch[3]-48)*10+((int)ch[4]-48);

         
                if(curt>=Integer.parseInt(currtime)+Integer.parseInt(dur))
                {



                    Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
         sql="Select * from user where user_id=?";
         pst = con.prepareStatement(sql);
         pst.setString(1,us);
         rs = pst.executeQuery();
//System.out.println(2);
         if(rs.next())
         {
             String wl=rs.getString("wallet_balance");
             double wal=Double.parseDouble(wl);
             System.out.println(wl);


            Class.forName("com.mysql.jdbc.Driver");
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
                    sql="update user set wallet_balance=? where user_id=?";
                    pst = con.prepareStatement(sql);
                    pst.setString(2,us);
                    pst.setString(1,Double.toString(wal-Double.parseDouble(dur)*10));
                    pst.executeUpdate();
                    System.out.println(Double.toString(wal-Double.parseDouble(dur)*10));
         }



                    Class.forName("com.mysql.jdbc.Driver");
                   Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
                   sql="update driver set busy=0,currlocation=? where serialnumber=?";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1,ne);
                    pst.setString(2,Integer.toString(i));
                    pst.executeUpdate();
                }
            }
        }
   }
   
}

catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}

try
{
   Class.forName("com.mysql.jdbc.Driver");
   Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
   String sql="Select * from user where user_id=?";
   PreparedStatement pst = con.prepareStatement(sql);
   pst.setString(1,uid);
   ResultSet rs = pst.executeQuery();
   if(rs.next())
   {
      String wall=rs.getString("wallet_balance");
      double wlt=Double.parseDouble(wall);
      if(wlt<300)
      {
          l1.setText("Your balance is less than 300!Click on ADD MONEY TO WALLET to add money");
          cb1.setEnabled(false);
          cb2.setEnabled(false);
          btn1.setEnabled(false);
      }

      else
      {
         int time[][]={
             {0,7,2,5,4,3},
             {7,0,9,2,8,1},
             {2,9,0,4,6,8},
             {5,2,4,0,6,9},
             {4,8,6,6,0,2},
             {3,1,8,9,2,0}
                      };
          String pick=(String) cb1.getSelectedItem();
          String drop=(String) cb2.getSelectedItem();
          int pk,dp;
          pk=Integer.parseInt(pick)-1;
          dp=Integer.parseInt(drop)-1;
          int curr[]=new int[6];
          double rate[]=new double[6];







try
{
    for(int i=1;i<7;i++){
   String sq="Select * from driver where serialnumber=?";
   Class.forName("com.mysql.jdbc.Driver");
   Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
   PreparedStatement ps = conn.prepareStatement(sq);
   String loc=Integer.toString(i);
   ps.setString(1,loc);
   ResultSet rss = ps.executeQuery();
   if(rss.next())
   {
       String curr_loc=rss.getString("currlocation");
       String rating=rss.getString("rate");
       String busy=rss.getString("busy");
       curr[i-1]=Integer.parseInt(curr_loc)-1;
       rate[i-1]=Double.parseDouble(rating);
       if(busy.equals("1"))
           curr[i-1]=-1;
       //System.out.println(curr_loc+" "+rating);
       
   }
}
    int in=-1,min=1000;
    double maxx=-1;
    for(int i=0;i<6;i++)
    {
        if(curr[i]!=-1)
        {
        if(time[pk][curr[i]]<min)
        {
            min=time[pk][curr[i]];
            maxx=rate[i];
            in=i;
        }
        else if(time[pk][curr[i]]==min && rate[i]>maxx)
        {
            min=time[pk][curr[i]];
            maxx=rate[i];
            in=i;
        }

        }
    }

    if(in==-1)
    {
        JOptionPane.showMessageDialog(null,"No drivers are available!");
    }

    else
    {
        total_time=time[pk][curr[in]]+time[pk][dp];
       /* Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
        PreparedStatement pstmt=null;
        pstmt=conn.prepareStatement("update driver set busy=1");*/
        dispose();
        driver_info d= new driver_info(Double.toString(in+1),drop,total_time,uid);
        d.setVisible(true);
        d.show_info();
    }



}
catch(Exception e)
{
  JOptionPane.showMessageDialog(null,e);
}

         
      }

   }
}
catch(Exception e)
{
  JOptionPane.showMessageDialog(null,e);


}
    }//GEN-LAST:event_btn1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();
Wallet_page pg=new Wallet_page(uid);
pg.wallet_balance();
pg.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   dispose();
Main_Form f=new Main_Form();
f.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    // End of variables declaration//GEN-END:variables

}
